preload = ~/.config/hypr/assets/_dark.png
preload = ~/.config/hypr/assets/_light.png
preload = ~/.config/hypr/assets/_black.png
preload = ~/.config/hypr/assets/_white.png
wallpaper = , ~/.config/hypr/assets/_dark.png