
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

$active_opa = 1
$inactive_opa = 1
$fullscreen_opa = 1.0
$floating_opa = 1.0

windowrule = center on,match:class (.*)
windowrule = opacity $active_opa $inactive_opa $fullscreen_opa,match:class (.*)

windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_title ^(timeshift)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_title ^(Picture-in-Picture)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(vlc)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(qt5ct)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(qt6ct)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(nwg-look)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(pavucontrol)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(blueman-manager)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(nm-applet)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(nm-connection-editor)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(mpv)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(imv)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(timeshift)(.*)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class (.*)(zathura)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class ^(calibre-ebook-viewer)$
windowrule = size monitor_w/2 monitor_h/2, float on,match:initial_class (.*)(Emulator)$


# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur on,match:namespace rofi
layerrule = blur on,match:namespace waybar
# layerrule = blur on,match:class notifications
