$black  = rgb(000000)
$white  = rgb(ffffff)
$bg     = rgb(4E4B42)
$fg     = rgb(ebdbb2)
$fg-1   = rgb(747063)
$bg-1   = rgb(B4AF9A)
$red    = rgb(cc241d)
$green  = rgb(98971a)
$yellow = rgb(d79921)
$blue   = rgb(458588)
$purple = rgb(b16286)
$aqua   = rgb(689d6a)
$gray   = rgb(bab59d)

$active   = rgb(B4AF9A)
$inactive = rgb(747063)

$wallpaper = $HOME/.config/hypr/assets/_dark.png
$bg-lock = $HOME/.config/hypr/assets/_dark.png