$bg     = rgb(ffffff)
$fg     = rgb(000000)
$red    = rgb(DA3434)
$green  = rgb(2D8655)
$yellow = rgb(926F16)
$blue   = rgb(427AA9)
$purple = rgb(B344CF)
$aqua   = rgb(4D7F80)
$gray   = rgb(687787)

$active             = rgb(000000)
$active-shadow      = rgb(687787)
$inactive           = rgb(ffffff)

$wallpaper = $HOME/.config/hypr/assets/_light.png
$bg-lock = $HOME/.config/hypr/assets/_light.png