$black  = rgb(000000)
$white  = rgb(ffffff)
$bg     = rgb(f9f5d7)
$fg     = rgb(4E4B42)
$fg-1   = rgb(dad4bb)
$bg-1   = rgb(747063)
$red    = rgb(9d0006)
$green  = rgb(79740e)
$yellow = rgb(b57614)
$blue   = rgb(076678)
$purple = rgb(8f3f71)
$aqua   = rgb(427b58)
$gray   = rgb(bab59d)

$active   = rgb(747063)
$inactive = rgb(dad4bb)

$wallpaper = $HOME/.config/hypr/assets/_light.png
$bg-lock = $HOME/.config/hypr/assets/_light.png