source = ~/.config/hypr/themes/_dark.conf

# █▀▀ █░█ █▀█ █▀ █▀█ █▀█
# █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

exec-once = hyprctl setcursor Bibata-Modern-Amber 14
exec-once = gsettings set org.gnome.desktop.interface cursor-size 14
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'Default'
# exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Amber'
# exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Material-Dark'


# █▀▀ █▀█ █▄░█ ▀█▀
# █▀░ █▄█ █░▀█ ░█░

exec-once = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
exec-once = gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 10'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMono Nerd Font 9'
exec-once = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec-once = gsettings set org.gnome.desktop.interface font-hinting 'full'

decoration {
    dim_special = 0.13
    blur {
        special = true
    }
}

general {
    gaps_in = 5
    gaps_out = 8
    border_size = 2
    layout = dwindle
    resize_on_border = true

    col.active_border = $active
    col.inactive_border = $inactive
}

decoration {
    rounding = 0

    blur {
        enabled = yes
        size = 5
        passes = 2
        noise= 0.05
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled = yes
        color = $active-shadow
        color_inactive = $inactive
        range = 1
        sharp = true
        ignore_window = false
        offset = 3 2
        render_power = 1
    }
}
