# gruvbox dark by morhetz, https://github.com/morhetz/gruvbox
# This work is licensed under the terms of the MIT license.
# For a copy, see https://opensource.org/licenses/MIT.

# @define-color fg-1 #dad4bb;
# @define-color bg-1 #B4AF9A;

foreground  #000000
background  #ffffff
selection_foreground  #ffffff
selection_background  #000000

cursor              #000000

color0              #687787
color1              #DA3434
color2              #427AA9
color3              #2D8655
color4              #926F16
color5              #B344CF
color6              #4D7F80
color7              #bfbfbf
color8              #4d4d4d
color9              #ff6e67
color10             #5af78e
color11             #f4f99d
color12             #51b6ff
color13             #ff92d0
color14             #9aedfe
color15             #e6e6e6
